name: "Build and Test"
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: "Build and Test"
    runs-on: "ubuntu-latest"
    permissions:
      pull-requests: "write"
      contents: "read"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: "Installs dependencies"
        run: "pnpm install"

      - name: "Docs check"
        run: |
          npx action-docs@latest
          if ! git diff --exit-code README.md; then
            echo "::error::README.md is out of date. Please run 'npx action-docs@latest' and commit the changes."
            exit 1
          fi

      - name: "Format"
        run: "pnpm run format"

      - name: "Lint"
        run: "pnpm run lint"

      - name: "Test"
        run: "pnpm run test"

      - name: "Build"
        run: "pnpm run build"
